import { DATA_SCHEMA_VERSION, ageBand, incomeBand, type DiagnosisFactV1, type FamilyProfile } from './data-platform-v1';
import type { Category, Satisfaction } from './mudagiri-diagnosis-v2';
import type { ToneMode } from './tone-mode-v3';
import type { TypeCode } from './result-payload-v2';
export function buildDiagnosisFactV1(x:{diagnosisId:string;prefecture:string;age:number;familyProfile:FamilyProfile;annualIncome:number;monthlyIncome:number;saving:number;emergencyMonths:number;toneMode:ToneMode;globalSatisfaction:1|2|3|4|5;typeCode:TypeCode;axes:Record<'fv'|'pi'|'au'|'se',number>;expenses:Record<Category,number>;unknown:Partial<Record<Category,boolean>>;satisfaction:Partial<Record<Category,Satisfaction>>;result:any;consent?:Partial<DiagnosisFactV1['consent']>}):DiagnosisFactV1{
 const household=x.familyProfile==='single'?'single':'multi'; const total=Object.values(x.expenses).reduce((a,b)=>a+b,0); const fcf=x.monthlyIncome-total-x.saving;
 const bucket=(c:Category):'cut'|'protected'|'unreviewed'|'clear'=>x.result.buckets.cut.some((z:any)=>z.category===c)?'cut':x.result.buckets.protected.some((z:any)=>z.category===c)?'protected':x.result.buckets.unreviewed.some((z:any)=>z.category===c)?'unreviewed':'clear';
 return {schemaVersion:DATA_SCHEMA_VERSION,diagnosisId:x.diagnosisId,createdAt:new Date().toISOString(),consent:{analytics:x.consent?.analytics??true,crm:x.consent?.crm??false,benchmark:x.consent?.benchmark??true},profile:{prefecture:x.prefecture,age:x.age,ageBand:ageBand(x.age),familyProfile:x.familyProfile,household,annualIncome:x.annualIncome,incomeBand:incomeBand(x.annualIncome)},finance:{monthlyTakeHomeIncome:x.monthlyIncome,monthlySavingInvestment:x.saving,freeCashFlow:fcf,emergencyMonths:x.emergencyMonths,savingRate:x.monthlyIncome>0?x.saving/x.monthlyIncome:null},experience:{toneMode:x.toneMode,globalSatisfaction:x.globalSatisfaction},type:{code:x.typeCode,axes:x.axes},battle:{score:x.result.battle.score,monthlyImprovement:x.result.improvement.monthly,annualImprovement:x.result.improvement.annual,fiveYearImprovement:x.result.improvement.fiveYear},categories:(Object.keys(x.expenses) as Category[]).map(category=>{const cmp=x.result.comparison.categories.find((z:any)=>z.category===category);const cut=x.result.buckets.cut.find((z:any)=>z.category===category);return {category,amount:x.unknown[category]?null:x.expenses[category],amountState:x.unknown[category]?'unknown':x.expenses[category]===0?'zero':'known',comparable:cmp?.comparable??null,difference:cmp?.difference??null,satisfaction:x.satisfaction[category],outcome:bucket(category),monthlyImprovement:cut?.monthlyImprovement??0}}),methodologyVersion:x.result.methodologyVersion};
}
