import React, { useEffect, useMemo, useState } from 'react';
import ResultScreenV2 from './ResultScreenV2';
import BattleSequenceV2 from './BattleSequenceV2';
import SatisfactionBattleV2 from './SatisfactionBattleV2';
import { resolveSatisfactionQuestions } from './satisfaction-resolver-v2';
import { resolveComparableV1 } from './comparable-resolver-v1';
import { selectBattleEncounters } from './battle-encounter-v2';
import { buildResultPayloadV2 } from './result-payload-v2';
import type { Category } from './mudagiri-diagnosis-v2';
import type { EducationStage } from './comparable-resolver-v1';
import { TYPE_QUESTIONS_V31, scoreTypeAnswersV31, TYPE_MODEL_VERSION, type RawAnswerV31 } from './type-questionnaire-v3.1';
import { UX_COPY_V2 } from './ux-copy-v2';
import { TONE_MODES, MODE_COPY, type ToneMode } from './tone-mode-v3';
import { acquisitionFromLocation, event, getOrCreateAnonymousUserId, newDiagnosisId } from './persistence-v1';
import { LocalPersistenceAdapterV2, productionPersistenceV2, type MudagiriPersistenceAdapterV2 } from './persistence-v2';
import LegalDisclosureV1 from './LegalDisclosureV1';

type Step='intro'|'profile'|'money'|'expenses'|'psych'|'satisfaction'|'battle'|'result';
type Household='single'|'multi';
type ExpenseMap=Record<Category,number>;
type UnknownMap=Partial<Record<Category,boolean>>;
const categories:Category[]=['rent','mobile','energy','insurance','sub','car','food','daily','fun','beautyFashion','childEducation','selfDevelopment'];
const labels:Record<Category,string>={rent:'家賃・住宅ローン',mobile:'通信費',energy:'光熱費',insurance:'保険料',sub:'サブスク',car:'車維持費（税・ローン・高速代を除く）',food:'食費',daily:'日用品',fun:'娯楽・交際費',beautyFashion:'美容・服飾',childEducation:'教育費',selfDevelopment:'自己投資'};
const emptyExpenses=Object.fromEntries(categories.map(c=>[c,0])) as ExpenseMap;
const prefectures=['北海道','青森県','岩手県','宮城県','秋田県','山形県','福島県','茨城県','栃木県','群馬県','埼玉県','千葉県','東京都','神奈川県','山梨県','長野県','新潟県','富山県','石川県','福井県','岐阜県','静岡県','愛知県','三重県','滋賀県','京都府','大阪府','兵庫県','奈良県','和歌山県','鳥取県','島根県','岡山県','広島県','山口県','徳島県','香川県','愛媛県','高知県','福岡県','佐賀県','長崎県','熊本県','大分県','宮崎県','鹿児島県','沖縄県'];
const steps:Step[]=['profile','money','expenses','psych','satisfaction'];
const expenseGroups:[string,Category[]][]=[['固定費',['rent','mobile','energy','insurance','sub']],['暮らし',['food','daily','car']],['楽しみ・未来',['fun','beautyFashion','childEducation','selfDevelopment']]];
const stageMeta:Partial<Record<Step,{no:string;title:string;enemy:string;copy:string}>>={profile:{no:'STAGE 1',title:'冒険者登録',enemy:'ムダの霧',copy:'まずは比較する世界線を決めよう。'},money:{no:'STAGE 2',title:'家計HP測定',enemy:'カツカツゴースト',copy:'家計の体力と守備力を測定する。'},expenses:{no:'STAGE 3',title:'ムダ敵探索',enemy:'ムダ軍団',copy:'ざっくりでOK。敵の気配を探知する。'},psych:{no:'STAGE 4',title:'マネー属性判定',enemy:'ココロミラー',copy:'8問であなたのお金の戦い方を見抜く。'},satisfaction:{no:'FINAL STAGE',title:'斬る・斬らない判定',enemy:'ラスボス「思い込み」',copy:'高いだけでは斬らない。価値がある支出は守る。'}};

function Num({label,value,onChange,compact=false,unknown=false,onUnknown}:{label:string;value:number;onChange:(n:number)=>void;compact?:boolean;unknown?:boolean;onUnknown?:()=>void}){return <div className="block"><label><span className={`mb-1.5 block font-bold ${compact?'text-xs':'text-sm'}`}>{label}</span><div className={`flex items-center rounded-sm border-2 border-zinc-700 bg-zinc-950 px-3 focus-within:border-amber-400 ${compact?'min-h-12':'min-h-14'}`}><span className="text-xs text-zinc-500">¥</span><input inputMode="numeric" value={value||''} onChange={e=>onChange(Number(e.target.value.replace(/\D/g,'')))} className={`w-full bg-transparent outline-none ${compact?'p-3 text-sm':'p-4'}`} placeholder={unknown?'金額不明':'0'} disabled={unknown}/></div></label>{onUnknown&&<button type="button" onClick={onUnknown} className={`mt-1.5 w-full rounded-sm border px-2 py-1.5 text-[11px] font-bold ${unknown?'border-amber-400 bg-amber-400/10 text-amber-300':'border-zinc-800 text-zinc-500'}`}>{unknown?'✓ 金額がわからない':'金額がわからない'}</button>}</div>}

export default function MudagiriAppV2({resolveComparable=resolveComparableV1,onLine,onEvent,persistence}:{resolveComparable?:(x:{household:Household;age:number;annualIncome:number;prefecture?:string;expenses:ExpenseMap;educationStage?:EducationStage})=>Partial<Record<Category,number|null>>;onLine?:(context?:Record<string,unknown>)=>void;onEvent?:(name:string,data?:Record<string,unknown>)=>void;persistence?:MudagiriPersistenceAdapterV2}){
 const [step,setStep]=useState<Step>('intro'); const [familyProfile,setFamilyProfile]=useState<'single'|'couple'|'children'|'other'>('single'); const [toneMode,setToneMode]=useState<ToneMode>('serious'); const [educationStage,setEducationStage]=useState<EducationStage|undefined>(); const [subUnused,setSubUnused]=useState(0); const [prefecture,setPrefecture]=useState('東京都'); const [household,setHousehold]=useState<Household>('single'); const [age,setAge]=useState(30); const [income,setIncome]=useState(0); const [saving,setSaving]=useState(0); const [emergency,setEmergency]=useState(3); const [expenses,setExpenses]=useState<ExpenseMap>(emptyExpenses);
 const [unknownExpenses,setUnknownExpenses]=useState<UnknownMap>({});
 const store=useMemo(()=>{
  if(persistence) return persistence;
  if(typeof window==='undefined') return undefined;
  return productionPersistenceV2(new LocalPersistenceAdapterV2());
 },[persistence]);
 const [anonymousUserId]=useState(()=>typeof window!=='undefined'?getOrCreateAnonymousUserId():'server');
 const [diagnosisId,setDiagnosisId]=useState(()=>typeof window!=='undefined'?newDiagnosisId():'server');
 const [savedDiagnosisId,setSavedDiagnosisId]=useState<string|null>(null);
 const [expenseGroupIndex,setExpenseGroupIndex]=useState(0);
 const [psychQuestionIndex,setPsychQuestionIndex]=useState(0);
 const [satisfactionQuestionIndex,setSatisfactionQuestionIndex]=useState(0);
 const [typeAnswers,setTypeAnswers]=useState<Record<string,RawAnswerV31|undefined>>({}); const [globalSat,setGlobalSat]=useState<1|2|3|4|5|undefined>(); const [catSat,setCatSat]=useState<Partial<Record<Category,'waste'|'inertia'|'satisfied'|'verySatisfied'>>>({});
 const progress=step==='intro'?0:step==='result'?100:((steps.indexOf(step)+1)/steps.length)*100;
 useEffect(()=>{window.scrollTo({top:0,behavior:'smooth'}); if(step!=='intro') onEvent?.('mudagiri_stage_view',{step});},[step,onEvent]);
 const emit=(name:string,data?:Record<string,unknown>)=>{onEvent?.(name,data); const persisted=['result_viewed','future_goal_selected','appointment_cta_clicked','appointment_booked','valid_appointment','conversion']; if(store&&persisted.includes(name)) store.appendEvent(event(anonymousUserId,diagnosisId,name as any,data));};
 const comparable=useMemo(()=>resolveComparable({household,age,annualIncome:income*12,prefecture,expenses,educationStage}),[household,age,income,prefecture,expenses,educationStage,resolveComparable]);
 const satisfactionQuestions=useMemo(()=>resolveSatisfactionQuestions(expenses,comparable),[expenses,comparable]);
 function next(){const idx=steps.indexOf(step); setStep(idx<steps.length-1?steps[idx+1]:'result')}
 const typeResult=scoreTypeAnswersV31(typeAnswers);
 const typeCode=typeResult.code;
 const result=(step==='battle'||step==='result')?buildResultPayloadV2({
   monthlyTakeHomeIncome:income,monthlySavingInvestment:saving,freeCashFlow:income-categories.reduce((sum,c)=>sum+(unknownExpenses[c]?0:expenses[c]),0)-saving,emergencyMonths:emergency,
   categories:categories.map(category=>({category,actual:expenses[category],comparable:comparable[category]??null,satisfaction:catSat[category],unusedAmount:category==='sub'?subUnused:undefined})),
   type:{code:typeCode,name:'',description:'あなたのお金の使い方を3つの軸から分類したタイプです。',axes:typeResult.axes,strength:typeResult.strength,nearMiddle:typeResult.nearMiddle,modelVersion:TYPE_MODEL_VERSION},globalSatisfaction:globalSat ?? 3,unknownCategories:categories.filter(c=>unknownExpenses[c])
 }):null;
 useEffect(()=>{if(step!=='result'||!result||!store||savedDiagnosisId===diagnosisId)return; const fact={diagnosisId,createdAt:new Date().toISOString(),schemaVersion:'MUDAGIRI_SHEET_V2' as const,typeModelVersion:TYPE_MODEL_VERSION,methodologyVersion:result.methodologyVersion,toneMode,household,age,monthlyIncome:income,monthlySaving:saving,type:{code:typeCode,axes:typeResult.axes,strength:typeResult.strength,nearMiddle:typeResult.nearMiddle},monthlyImprovement:result.improvement.monthly,needsReview:result.needsReview,expenses,typeAnswers,anonymousUserId,acquisition:acquisitionFromLocation()}; Promise.all([store.saveDiagnosis(fact),store.appendEvent(event(anonymousUserId,diagnosisId,'diagnosis_completed',{typeCode,typeModelVersion:TYPE_MODEL_VERSION,battleScore:result.battle.score,monthlyImprovement:result.improvement.monthly,toneMode}))]).then(()=>setSavedDiagnosisId(diagnosisId));},[step,result,store,savedDiagnosisId,diagnosisId,anonymousUserId,household,age,income,saving,typeCode,typeResult.axes,typeResult.strength,typeResult.nearMiddle,expenses,typeAnswers,toneMode]);
 if(step==='result'&&result)return <ResultScreenV2 result={result} toneMode={toneMode} familyProfile={familyProfile} onLine={(context)=>{store?.appendEvent(event(anonymousUserId,diagnosisId,'line_clicked',context));if(onLine){onLine({...context,anonymousUserId,diagnosisId})}else if(typeof window!=='undefined'){window.location.href='https://lin.ee/ZeLu7i6'}}} onEvent={emit}/>;
 return <main className="mudagiri-shell min-h-screen bg-zinc-950 text-zinc-100"><div className="mx-auto max-w-md px-4 py-6">{step!=='intro'&&<><div className="mb-2 flex items-center justify-between text-[11px] font-bold text-zinc-500"><span>QUEST TIME 約2分</span><span>{Math.min(steps.indexOf(step)+1,5)} / 5</span></div><div className="quest-meter mb-4 h-1.5 overflow-hidden border border-zinc-800 bg-zinc-950"><div className="h-full bg-amber-400 transition-all" style={{width:`${progress}%`}}/></div>{stageMeta[step]&&<StageBanner {...stageMeta[step]!}/>}</>}
 {step==='intro'&&<section className="pt-2 text-center"><div className="relative mb-5 aspect-[4/5] overflow-hidden rounded-sm border-2 border-zinc-700"><img src="./assets/page/hero-key-visual.png" alt="ムダギリ診断の冒険世界" className="absolute inset-0 h-full w-full object-cover object-center image-pixelated"/><div className="absolute inset-x-0 bottom-0 h-1/2 bg-gradient-to-t from-zinc-950 via-zinc-950/55 to-transparent"/><div className="absolute inset-x-4 bottom-4 text-left"><div className="text-[10px] font-black tracking-[.2em] text-amber-300">2 MIN MONEY QUEST</div><div className="mt-1 text-xl font-black text-white [text-shadow:2px_2px_0_#18181b]">好きなものは、斬らない。<br/>ムダだけ、斬る。</div></div></div><div className="text-xs font-black tracking-[.18em] text-amber-400">{UX_COPY_V2.intro.eyebrow}</div><h1 className="mt-4 text-4xl font-black leading-tight">君の家計は<br/><span className="text-amber-400">モンスターだらけ!?</span></h1><p className="mt-3 text-sm leading-6 text-zinc-400">{UX_COPY_V2.intro.body}</p><p className="rpg-dialogue mt-3 px-3 py-2 text-sm font-bold text-zinc-200">「収入はあるのに、思ったほどお金が残らない」なら要注意。</p><div className="mt-6 rounded-sm border border-zinc-700 bg-zinc-900 p-4 text-left"><div className="text-xs font-black text-amber-400">ムダギリくん</div><p className="mt-2 text-sm leading-6 text-zinc-300">「高い支出＝悪」じゃない。大事にしてる金は守る。<br/><b className="text-white">好きなものは、斬らない。ムダだけ、斬る。</b></p></div><div className="rpg-status mt-5 text-xs"><span>TIME 約2分</span><span>SCAN 12項目</span><span>TITLE 8種</span></div><div className="mt-6 text-left"><div className="text-center text-lg font-black">🪓 今日、どこまで斬られますか？</div><p className="mt-1 text-center text-[11px] text-zinc-500">診断結果・金額はどのモードでも同じ。言い方だけ変わります。</p><div className="mt-3 grid gap-2">{(Object.entries(TONE_MODES) as [ToneMode,typeof TONE_MODES[ToneMode]][]).map(([key,m])=><button key={key} onClick={()=>{setToneMode(key);onEvent?.('mudagiri_mode_selected',{mode:key});}} className={`rpg-command w-full border-0 p-3 text-left transition ${toneMode===key?'is-selected':''}`}><div className="flex items-center justify-between"><div className="font-black">{m.icon} {m.name}</div>{'recommended' in m&&m.recommended&&<span className="border border-amber-400 px-2 py-1 text-[10px] font-black text-amber-400">推奨</span>}</div><div className="mt-1 text-xs font-bold text-zinc-300">「{m.choice}」</div><div className="mt-1 text-[11px] text-zinc-500">{m.tagline}</div></button>)}</div><div className="rpg-dialogue mt-4 p-3 text-xs leading-5 text-zinc-300"><b className="text-amber-400">ムダギリくん：</b>{MODE_COPY[toneMode].start}</div></div><button onClick={()=>{onEvent?.('mudagiri_start',{mode:toneMode,diagnosisId});store?.appendEvent(event(anonymousUserId,diagnosisId,'diagnosis_started',{mode:toneMode,...acquisitionFromLocation()}));setStep('profile')}} className="rpg-primary mt-7 w-full p-4 font-black">▶ 診断クエストを開始</button><p className="mt-3 text-[11px] text-zinc-600">登録不要・約2分</p><LegalDisclosureV1/></section>}
 {step==='profile'&&<section><h2 className="text-2xl font-black">まずはあなたのこと</h2><div className="mt-6 space-y-5"><div><div className="mb-2 text-sm font-bold">世帯</div><div className="grid grid-cols-2 gap-2">{[['single','ひとり暮らし'],['couple','夫婦・パートナー'],['children','子どもあり'],['other','その他']].map(([k,v])=><button key={k} onClick={()=>{setFamilyProfile(k as any);setHousehold(k==='single'?'single':'multi')}} className={`rounded-sm border p-4 font-bold ${familyProfile===k?'border-amber-400 bg-amber-400 text-zinc-950':'border-zinc-700'}`}>{v}</button>)}</div></div><label className="block"><span className="mb-2 block text-sm font-bold">都道府県</span><select value={prefecture} onChange={e=>setPrefecture(e.target.value)} className="w-full rounded-sm border border-zinc-700 bg-zinc-950 p-4">{prefectures.map(p=><option key={p}>{p}</option>)}</select></label><label className="block"><span className="mb-2 block text-sm font-bold">年齢</span><input type="number" value={age} onChange={e=>setAge(+e.target.value)} className="w-full rounded-sm border border-zinc-700 bg-zinc-950 p-4"/></label></div><Next onClick={next}/></section>}
 {step==='money'&&<section><h2 className="text-2xl font-black">家計の体力をチェック</h2><div className="mt-3 rounded-sm border border-zinc-800 bg-zinc-900 p-3 text-xs leading-5 text-zinc-400">🔒 収入の多さを評価するためではありません。<b className="text-zinc-200">家計にどれだけ余力があるか</b>を見るために使います。</div><div className="mt-6 space-y-5"><Num label="月の手取り収入" value={income} onChange={setIncome}/><Num label="毎月の貯蓄・投資" value={saving} onChange={setSaving}/><div><div className="mb-2 text-sm font-bold">収入が止まったら、すぐ使える貯金は？</div><select value={emergency} onChange={e=>setEmergency(+e.target.value)} className="w-full rounded-sm border border-zinc-700 bg-zinc-950 p-4"><option value={0}>ほぼない</option><option value={2}>1〜3ヶ月</option><option value={4.5}>3〜6ヶ月</option><option value={9}>半年〜1年</option><option value={12}>1年以上</option></select></div></div><button disabled={income<=0} onClick={next} className="mt-8 w-full rounded-sm bg-amber-400 p-4 font-black text-zinc-950 disabled:cursor-not-allowed disabled:opacity-30">次へ</button>{income<=0&&<p className="mt-2 text-center text-xs text-zinc-600">手取り収入だけ入力してください</p>}</section>}
 {step==='expenses'&&<section><div className="flex items-end justify-between gap-3"><div><h2 className="text-2xl font-black">{UX_COPY_V2.expenses.title}</h2><p className="mt-2 text-sm text-zinc-500">{UX_COPY_V2.expenses.body}</p></div><div className="shrink-0 border border-zinc-800 bg-zinc-950 px-3 py-1.5 text-xs font-bold text-zinc-400">{expenseGroupIndex+1} / 3</div></div><div className="mt-5 flex gap-2">{expenseGroups.map(([group],i)=><button key={group} onClick={()=>setExpenseGroupIndex(i)} aria-label={`${group}を入力`} className={`h-2 flex-1 border border-zinc-800 ${i<=expenseGroupIndex?'bg-amber-400':'bg-zinc-950'}`}/>)}</div><div className="mt-6 rounded-sm border border-zinc-800 bg-zinc-900 p-4"><div className="mb-1 text-xs font-black tracking-wider text-amber-400">{expenseGroups[expenseGroupIndex][0]}</div><p className="mb-4 text-xs leading-5 text-zinc-500">月額をざっくり入力。ない項目は0円でOK。金額を把握していない項目は「金額がわからない」を選べます。</p><div className="grid grid-cols-2 gap-x-3 gap-y-4">{expenseGroups[expenseGroupIndex][1].map(c=><Num compact key={c} label={labels[c]} value={expenses[c]} unknown={!!unknownExpenses[c]} onUnknown={()=>setUnknownExpenses(x=>({...x,[c]:!x[c]}))} onChange={n=>{setExpenses(x=>({...x,[c]:n}));setUnknownExpenses(x=>({...x,[c]:false}))}}/>)}</div>{expenseGroupIndex===2&&expenses.childEducation>0&&<label className="mt-5 block rounded-sm border border-zinc-800 bg-zinc-950 p-4"><span className="mb-2 block text-sm font-bold">教育費の学校区分 <span className="font-normal text-zinc-500">（任意）</span></span><select value={educationStage??''} onChange={e=>setEducationStage((e.target.value||undefined) as EducationStage|undefined)} className="w-full rounded-sm border border-zinc-700 bg-zinc-950 p-3"><option value="">比較しない</option><option value="publicKindergarten">公立幼稚園</option><option value="privateKindergarten">私立幼稚園</option><option value="publicElementary">公立小学校</option><option value="privateElementary">私立小学校</option><option value="publicJuniorHigh">公立中学校</option><option value="privateJuniorHigh">私立中学校</option><option value="publicHigh">公立高校</option><option value="privateHigh">私立高校</option></select><span className="mt-2 block text-xs text-zinc-500">平均超過だけでムダ判定はしません。</span></label>}</div><div className="mt-4 text-center text-xs text-zinc-600">{expenseGroups.slice(expenseGroupIndex+1).reduce((n,[,xs])=>n+xs.length,0)>0?`あと ${expenseGroups.slice(expenseGroupIndex+1).reduce((n,[,xs])=>n+xs.length,0)} 項目`:'12項目入力完了'}</div>{expenseGroupIndex<2?<button onClick={()=>{setExpenseGroupIndex(i=>i+1);window.scrollTo({top:0,behavior:'smooth'})}} className="mt-4 w-full rounded-sm bg-amber-400 p-4 font-black text-zinc-950">次の項目へ</button>:<button onClick={()=>{setExpenseGroupIndex(0);next()}} className="mt-4 w-full rounded-sm bg-amber-400 p-4 font-black text-zinc-950">12項目をスキャンする</button>}{expenseGroupIndex>0&&<button onClick={()=>setExpenseGroupIndex(i=>i-1)} className="mt-2 w-full p-3 text-xs font-bold text-zinc-500">← 前の項目に戻る</button>}</section>}
 {step==='psych'&&<section><div className="flex items-end justify-between gap-3"><div><div className="mb-5 rounded-sm border border-amber-400/30 bg-amber-400/5 p-4"><div className="text-xs font-black text-amber-400">👾 12項目のスキャン完了</div><div className="mt-1 font-black">敵影を検知。だが、まだ斬らない。</div><p className="mt-1 text-xs leading-5 text-zinc-400">あなたが何に価値を感じる人か分からないまま斬るのは雑すぎる。あと8問でマネー属性を判定します。</p></div><h2 className="text-2xl font-black">8問で、お金の性格を診断</h2><p className="mt-2 text-sm text-zinc-500">考えすぎなくてOK。いちばん近い方を直感で。</p></div><div className="shrink-0 border border-zinc-800 bg-zinc-950 px-3 py-1.5 text-xs font-black text-amber-400">{psychQuestionIndex+1} / 8</div></div><div className="quest-meter mt-5 h-2 overflow-hidden border border-zinc-800 bg-zinc-950"><div className="h-full bg-amber-400 transition-all duration-300" style={{width:`${((psychQuestionIndex+1)/TYPE_QUESTIONS_V31.length)*100}%`}}/></div><div className="mt-7">{(()=>{const q=TYPE_QUESTIONS_V31[psychQuestionIndex];return <TypeQ q={q} value={typeAnswers[q.id]} onChange={v=>{setTypeAnswers(x=>({...x,[q.id]:v}));onEvent?.('type_question_answered',{question:q.id,index:psychQuestionIndex+1});window.setTimeout(()=>{if(psychQuestionIndex<TYPE_QUESTIONS_V31.length-1){setPsychQuestionIndex(i=>Math.min(i+1,TYPE_QUESTIONS_V31.length-1));window.scrollTo({top:0,behavior:'smooth'})}},140)}}/>})()}</div><div className="mt-5 flex items-center justify-between"><button disabled={psychQuestionIndex===0} onClick={()=>setPsychQuestionIndex(i=>Math.max(0,i-1))} className="p-3 text-xs font-bold text-zinc-500 disabled:opacity-0">← 1問戻る</button><span className="text-[11px] text-zinc-600">回答は戻って変更できます</span></div>{psychQuestionIndex===TYPE_QUESTIONS_V31.length-1&&typeAnswers[TYPE_QUESTIONS_V31[7].id]!==undefined&&<button disabled={TYPE_QUESTIONS_V31.some(q=>typeAnswers[q.id]===undefined)} onClick={()=>{setPsychQuestionIndex(0);next()}} className="mt-5 w-full rounded-sm bg-amber-400 p-4 font-black text-zinc-950 disabled:cursor-not-allowed disabled:opacity-30">属性判定を完了する →</button>}</section>}
 {step==='satisfaction'&&<section><h2 className="text-2xl font-black">{UX_COPY_V2.satisfaction.title}</h2><p className="mt-2 text-sm text-zinc-500">{UX_COPY_V2.satisfaction.body}</p>{!globalSat?<div className="mt-6"><div className="mb-2 text-sm font-bold">{UX_COPY_V2.satisfaction.global}</div><div className="grid gap-2">{[['かなり満足',1],['まあ満足',2],['普通',3],['少しモヤる',4],['結構ムダがある気がする',5]].map(([t,v])=><button key={String(v)} onClick={()=>{setGlobalSat(v as any);onEvent?.('mudagiri_global_satisfaction',{value:v});}} className="rpg-command w-full border-0 p-3 text-left text-sm font-bold active:translate-x-0.5">{t}</button>)}</div></div>:satisfactionQuestions.length>0&&satisfactionQuestionIndex<satisfactionQuestions.length?<SatisfactionBattleV2 questions={satisfactionQuestions} index={satisfactionQuestionIndex} values={catSat} onBack={()=>setSatisfactionQuestionIndex(i=>Math.max(0,i-1))} onPick={(category,value)=>{setCatSat(x=>({...x,[category]:value}));onEvent?.('mudagiri_value_check',{category,value,index:satisfactionQuestionIndex+1,total:satisfactionQuestions.length});setTimeout(()=>setSatisfactionQuestionIndex(i=>Math.min(satisfactionQuestions.length,i+1)),140);}}/>:<div className="mt-6"><div className="rounded-sm border border-emerald-900/60 bg-emerald-950/20 p-4"><div className="font-black text-emerald-300">✓ 価値観チェック完了</div><p className="mt-1 text-xs leading-5 text-zinc-500">満足している支出は守り、惰性や後悔がある部分だけを判定に使います。</p></div>{expenses.sub>0&&<div className="mt-5"><Num label="ほぼ使っていないサブスクの月額" value={subUnused} onChange={n=>setSubUnused(Math.min(n,expenses.sub))}/><p className="mt-2 text-xs text-zinc-500">使っていないと申告した実額だけを候補にします。利用中のサブスクは勝手に斬りません。</p></div>}<button onClick={()=>setStep('battle')} className="mt-8 w-full rounded-sm bg-amber-400 p-4 font-black text-zinc-950">{UX_COPY_V2.satisfaction.cta}</button></div>}</section>}
 {step==='battle'&&result&&<BattleSequenceV2 toneMode={toneMode} items={selectBattleEncounters(result,expenses,comparable,3)} onComplete={()=>setStep('result')} onEvent={onEvent}/>}
 </div></main>
}
function Next({onClick}:{onClick:()=>void}){return <button onClick={onClick} className="mt-8 w-full rounded-sm bg-amber-400 p-4 font-black text-zinc-950">次へ</button>}
function TypeQ({q,value,onChange}:{q:any;value?:RawAnswerV31;onChange:(v:RawAnswerV31)=>void}){
 const opts=[{choice:'a' as const,strength:2 as const,label:'かなり近い'},{choice:'a' as const,strength:1 as const,label:'やや近い'},{choice:'b' as const,strength:1 as const,label:'やや近い'},{choice:'b' as const,strength:2 as const,label:'かなり近い'}];
 return <div className="mt-4"><div className="text-sm font-black leading-6">{q.prompt}</div><div className="mt-3 grid grid-cols-2 gap-2">{opts.map(o=><button key={o.choice+o.strength} onClick={()=>onChange({choice:o.choice,strength:o.strength})} className={`rpg-command p-3 text-left text-xs ${value?.choice===o.choice&&value?.strength===o.strength?'is-selected':''}`}><b>{q[o.choice].text}</b><span className="mt-1 block text-[10px] text-zinc-500">{o.label}</span></button>)}</div></div>
}
function StageBanner({no,title,enemy,copy}:{no:string;title:string;enemy:string;copy:string}){return <div className="mb-6 overflow-hidden rounded-sm border border-zinc-800 bg-zinc-900"><div className="flex items-center justify-between border-b border-zinc-800 px-4 py-2 text-[10px] font-black tracking-[.16em]"><span className="text-amber-400">{no}</span><span className="text-zinc-600">MUDAGIRI QUEST</span></div><div className="p-4"><div className="flex items-center gap-3"><div className="rpg-enemy-marker grid h-11 w-11 shrink-0 place-items-center text-xl">◆</div><div><div className="text-lg font-black">{title}</div><div className="text-xs font-bold text-rose-300">{enemy} があらわれた！</div></div></div><p className="mt-3 text-xs leading-5 text-zinc-500">{copy}</p></div></div>}
function MiniStat({top,bottom}:{top:string;bottom:string}){return <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-3"><div className="font-black text-amber-400">{top}</div><div className="mt-1 text-zinc-500">{bottom}</div></div>}
