import {resolveComparableV1,__frozenComparableAudit} from './comparable-resolver-v1';
import {runDiagnosisV2} from './mudagiri-diagnosis-v2';
let pass=0; const ok=(x:boolean,m:string)=>{if(!x)throw new Error(m);pass++};
const car=resolveComparableV1({household:'multi',age:40,annualIncome:8_000_000,expenses:{car:30000}});
ok(car.car===14100,'car benchmark');
const edu=resolveComparableV1({household:'multi',age:40,annualIncome:8_000_000,expenses:{childEducation:50000},educationStage:'publicElementary'});
ok(edu.childEducation===Math.round(366599/12),'corrected public elementary');
const noEdu=resolveComparableV1({household:'multi',age:40,annualIncome:8_000_000,expenses:{childEducation:50000}});
ok(noEdu.childEducation===null,'education needs stage');
const cats:any[]=['mobile','energy','sub','car','food','daily','fun','beautyFashion','rent','insurance','childEducation','selfDevelopment'].map(category=>({category,actual:0,comparable:null}));
cats.find(x=>x.category==='rent').actual=200000;
cats.find(x=>x.category==='insurance').actual=80000;
cats.find(x=>x.category==='sub').actual=10000; cats.find(x=>x.category==='sub').unusedAmount=6000;
const d=runDiagnosisV2({monthlyTakeHomeIncome:500000,monthlySavingInvestment:50000,freeCashFlow:100000,emergencyMonths:6,categories:cats});
ok(d.categories.find(x=>x.category==='rent')!.reducible===0,'rent no auto reducible');
ok(d.needsReview.some(x=>x.category==='rent'),'high rent review');
ok(d.categories.find(x=>x.category==='insurance')!.reducible===0,'insurance zero');
ok(d.categories.find(x=>x.category==='sub')!.reducible===6000,'unused sub exact');
ok(!d.improvement.excludedCategories.includes('sub'),'sub included');
ok(__frozenComparableAudit.CAR_MONTHLY_BENCHMARK===14100,'audit car');
console.log(`special policy PASS ${pass}/9`);
