export const PILOT_VERSION = "V4.3_IMPLEMENTATION_CANDIDATE" as const;
export const PILOT_ITEMS = [
  {"item_id":"F01","family":"CORE","construct":"FUTURE","text":"今すぐ必要のないお金は、1年以上先に使う可能性も考えて残しておく方だ。","behavior_options":""},
  {"item_id":"F02","family":"CORE","construct":"FUTURE","text":"日々のお金の使い方でも、数年先にやりたいことを意識する方だ。","behavior_options":""},
  {"item_id":"F03","family":"CORE","construct":"FUTURE","text":"近いうちに大きな予定があると、欲しいものでも後回しにする方だ。","behavior_options":""},
  {"item_id":"F04","family":"CORE","construct":"FUTURE","text":"臨時収入が入ったら、今使う前に「数か月先のためにいくら残すか」を考える。","behavior_options":""},
  {"item_id":"F05","family":"CORE","construct":"FUTURE","text":"今の満足を少し我慢してでも、将来の選択肢を狭めないようにしたい。","behavior_options":""},
  {"item_id":"I01","family":"CORE","construct":"IMMEDIATE","text":"将来のために残す選択肢があっても、今の生活が大きく良くなるなら、今使う方を選びやすい。","behavior_options":""},
  {"item_id":"I02","family":"CORE","construct":"IMMEDIATE","text":"期限のある体験や機会は、後からでもできることより先に選びたい。","behavior_options":""},
  {"item_id":"I03","family":"CORE","construct":"IMMEDIATE","text":"同じくらい価値があるなら、後で使えるものより今使えるものを選びたい。","behavior_options":""},
  {"item_id":"I04","family":"CORE","construct":"IMMEDIATE","text":"臨時収入が入ったら、残す額より先に「今なら何に使いたいか」を考える。","behavior_options":""},
  {"item_id":"I05","family":"CORE","construct":"IMMEDIATE","text":"少し高くついても、必要だと思った時にすぐ使える方を選びやすい。","behavior_options":""},
  {"item_id":"N01","family":"CORE","construct":"INTUITION","text":"候補に大きな差がなければ、最後は最初に惹かれた方を選ぶことが多い。","behavior_options":""},
  {"item_id":"N02","family":"CORE","construct":"INTUITION","text":"人から十分な理由を聞いても、自分でピンとこない選択肢は選びにくい。","behavior_options":""},
  {"item_id":"N03","family":"CORE","construct":"INTUITION","text":"数字や条件で少し不利でも、自分に合っていると感じる方を選びやすい。","behavior_options":""},
  {"item_id":"N04","family":"CORE","construct":"INTUITION","text":"理由をうまく説明できなくても、何となく違和感がある選択肢は避けることが多い。","behavior_options":""},
  {"item_id":"N05","family":"CORE","construct":"INTUITION","text":"情報を集めても優劣がつかないときは、最後は自分の感覚で決める方だ。","behavior_options":""},
  {"item_id":"D01","family":"CORE","construct":"DELIBERATION","text":"決めるまで少し時間が延びても、候補を並べて比べてから選びたい。","behavior_options":""},
  {"item_id":"D02","family":"CORE","construct":"DELIBERATION","text":"説明を聞いて好印象でも、条件に分からない点が残ったままでは申し込みにくい。","behavior_options":""},
  {"item_id":"D03","family":"CORE","construct":"DELIBERATION","text":"金額が大きくなるほど、良い点と気になる点を一度整理して考える。","behavior_options":""},
  {"item_id":"D04","family":"CORE","construct":"DELIBERATION","text":"魅力を感じていても、判断材料が足りなければいったん保留することが多い。","behavior_options":""},
  {"item_id":"D05","family":"CORE","construct":"DELIBERATION","text":"候補が似ているほど、先に「何を優先するか」を決めてから選ぶことが多い。","behavior_options":""},
  {"item_id":"M01","family":"CORE","construct":"MONITORING","text":"今月あとどのくらい使えそうか聞かれれば、大体すぐ答えられる。","behavior_options":""},
  {"item_id":"M02","family":"CORE","construct":"MONITORING","text":"毎月決まって出ていくお金が合計どのくらいか、ざっくり把握している。","behavior_options":""},
  {"item_id":"M03","family":"CORE","construct":"MONITORING","text":"カードやキャッシュレス中心でも、今月の支出ペースはなんとなく分かっている。","behavior_options":""},
  {"item_id":"M04","family":"CORE","construct":"MONITORING","text":"いつもより支出が増えていると、月の途中でも気づくことが多い。","behavior_options":""},
  {"item_id":"M05","family":"CORE","construct":"MONITORING","text":"直近1週間で何にいくらくらい使ったか、振り返れば大まかに言える。","behavior_options":""},
  {"item_id":"P01","family":"CORE","construct":"PERIODIC","text":"残高や明細は、普段から追うより、必要になったときにまとめて見る方だ。","behavior_options":""},
  {"item_id":"P02","family":"CORE","construct":"PERIODIC","text":"給料日や月末など、区切りのタイミングでお金の状態を確認することが多い。","behavior_options":""},
  {"item_id":"P03","family":"CORE","construct":"PERIODIC","text":"大きな支払いや予定がある前後で、残高や明細を確認することが多い。","behavior_options":""},
  {"item_id":"P04","family":"CORE","construct":"PERIODIC","text":"お金の確認は、その都度ではなく、週1回など自分で決めた間隔で行う方だ。","behavior_options":""},
  {"item_id":"P05","family":"CORE","construct":"PERIODIC","text":"利用通知や明細がたまっても、その都度見るより後からまとめて確認する方だ。","behavior_options":""},
  {"item_id":"R01","family":"CORE","construct":"DRIVE","text":"自由に使えるお金があれば、自分のスキルや仕事に役立つ使い道を優先したい。","behavior_options":""},
  {"item_id":"R02","family":"CORE","construct":"DRIVE","text":"目標を早く進められるなら、有料の道具やサービスを使うことに抵抗が少ない。","behavior_options":""},
  {"item_id":"R03","family":"CORE","construct":"DRIVE","text":"余裕資金ができると、それを次の挑戦や機会のための元手として見やすい。","behavior_options":""},
  {"item_id":"R04","family":"CORE","construct":"DRIVE","text":"結果が確実でなくても、自分の可能性が広がりそうならお金を使いやすい。","behavior_options":""},
  {"item_id":"R05","family":"CORE","construct":"DRIVE","text":"新しい人・場所・環境に出会えて、次の機会につながりそうなら、お金を使う価値を感じる。","behavior_options":""},
  {"item_id":"E01","family":"CORE","construct":"ENJOY","text":"同じ金額を使うなら、モノを増やすより、楽しめる体験に使いたい。","behavior_options":""},
  {"item_id":"E02","family":"CORE","construct":"ENJOY","text":"友人や家族と一緒に過ごす時間には、モノを買うよりお金を使いたい。","behavior_options":""},
  {"item_id":"E03","family":"CORE","construct":"ENJOY","text":"同じくらい役に立つなら、使うたび気分が上がる方を選びたくなる。","behavior_options":""},
  {"item_id":"E04","family":"CORE","construct":"ENJOY","text":"一人で楽しむ体験でも、形に残らなくても満足できるなら、お金を使う価値を感じる。","behavior_options":""},
  {"item_id":"E05","family":"CORE","construct":"ENJOY","text":"あとで思い出として残りそうなことには、形に残るものと同じくらいお金を使う価値を感じる。","behavior_options":""},
  {"item_id":"S01","family":"CORE","construct":"SECURE","text":"急な出費があっても生活が崩れないくらいの余裕があると安心する。","behavior_options":""},
  {"item_id":"S02","family":"CORE","construct":"SECURE","text":"大きく得られる可能性より、損したときの幅が小さいことを重視する。","behavior_options":""},
  {"item_id":"S03","family":"CORE","construct":"SECURE","text":"毎月の支払額は、変動するより一定の方が安心できる。","behavior_options":""},
  {"item_id":"S04","family":"CORE","construct":"SECURE","text":"必要なときにすぐ使えない形にお金を置くのは、不安を感じる。","behavior_options":""},
  {"item_id":"S05","family":"CORE","construct":"SECURE","text":"途中でやめにくい長期契約は、内容が魅力的でも慎重になる方だ。","behavior_options":""},
  {"item_id":"O01","family":"CORE","construct":"OPTIMIZE","text":"安い方かどうかより、使う回数や期間まで考えて『元が取れそうな方』を選びたい。","behavior_options":""},
  {"item_id":"O02","family":"CORE","construct":"OPTIMIZE","text":"払った金額に対して、その機能やサービスをどれだけ使い切れるかが気になる。","behavior_options":""},
  {"item_id":"O03","family":"CORE","construct":"OPTIMIZE","text":"使う頻度が落ちたサービスは、料金が小さくてもそのまま払い続けるのが気になる。","behavior_options":""},
  {"item_id":"O04","family":"CORE","construct":"OPTIMIZE","text":"安くても、使いにくくて買い直しそうなら、最初から少し高い方を選びたい。","behavior_options":""},
  {"item_id":"O05","family":"CORE","construct":"OPTIMIZE","text":"機能が多い「全部入り」より、自分が使う機能に絞られたプランの方が魅力的だ。","behavior_options":""},
  {"item_id":"SW01","family":"SWITCH","construct":"SWITCH_TIME","text":"A：今の生活を少し便利にする\nB：3〜6か月後の予定に使えるよう残す","behavior_options":""},
  {"item_id":"SW02","family":"SWITCH","construct":"SWITCH_TIME","text":"A：今回の旅行をもう少し充実させる\nB：3〜6か月後の別の予定に使える余裕を残す","behavior_options":""},
  {"item_id":"SW03","family":"SWITCH","construct":"SWITCH_TIME","text":"A：前から気になっていたものに使う\nB：3〜6か月後の予定に使えるよう残す","behavior_options":""},
  {"item_id":"SW04","family":"SWITCH","construct":"SWITCH_TIME","text":"A：3か月以内に役立ち始める方\nB：1年以上先でも役立ち続ける方","behavior_options":""},
  {"item_id":"SW05","family":"SWITCH","construct":"SWITCH_DECISION","text":"普段の買い物で、候補が2つまで絞れたら、どちらに近いですか？\nA：自分にしっくりくる方を選ぶ\nB：条件を比べて納得できる方を選ぶ","behavior_options":""},
  {"item_id":"SW06","family":"SWITCH","construct":"SWITCH_DECISION","text":"金額の大きい契約で、候補が2つまで絞れたら、どちらに近いですか？\nA：自分にしっくりくる方を選ぶ\nB：条件を比べて納得できる方を選ぶ","behavior_options":""},
  {"item_id":"B01","family":"BEHAVIOR","construct":"BEHAVIOR","text":"過去30日で、カードや口座の利用明細を自分から確認したのはどのくらいですか？","behavior_options":"0回 / 1回 / 2〜3回 / 4〜7回 / 8〜15回 / 16回以上"},
  {"item_id":"B02","family":"BEHAVIOR","construct":"BEHAVIOR","text":"過去6か月のうち、収入が入ったあと、使う前に貯蓄・積立・投資へ回した月はいくつありましたか？","behavior_options":"0か月 / 1か月 / 2〜3か月 / 4〜5か月 / 6か月"},
  {"item_id":"B03","family":"BEHAVIOR","construct":"BEHAVIOR","text":"過去30日で、買う予定ではなかった3,000円以上のものを、その場で購入したことは何回ありましたか？","behavior_options":"0回 / 1回 / 2〜3回 / 4〜5回 / 6回以上"},
  {"item_id":"B04","family":"BEHAVIOR","construct":"BEHAVIOR","text":"過去12か月で、通信・サブスク・保険などを実際に解約・変更して固定費を見直したことは何件ありましたか？","behavior_options":"0件 / 1件 / 2件 / 3件 / 4件以上"}
] as const;

export const OMISSION_ALLOCATION = {
  A:{FUTURE:"F01",IMMEDIATE:"I03",INTUITION:"N02",DELIBERATION:"D05",MONITORING:"M03",PERIODIC:"P05",DRIVE:"R04",ENJOY:"E03",SECURE:"S03",OPTIMIZE:"O03"},
  B:{FUTURE:"F04",IMMEDIATE:"I04",INTUITION:"N01",DELIBERATION:"D02",MONITORING:"M01",PERIODIC:"P01",DRIVE:"R03",ENJOY:"E04",SECURE:"S05",OPTIMIZE:"O04"},
  C:{FUTURE:"F03",IMMEDIATE:"I02",INTUITION:"N03",DELIBERATION:"D03",MONITORING:"M02",PERIODIC:"P02",DRIVE:"R05",ENJOY:"E02",SECURE:"S02",OPTIMIZE:"O02"},
  D:{FUTURE:"F05",IMMEDIATE:"I01",INTUITION:"N05",DELIBERATION:"D04",MONITORING:"M04",PERIODIC:"P04",DRIVE:"R01",ENJOY:"E01",SECURE:"S01",OPTIMIZE:"O01"},
  E:{FUTURE:"F02",IMMEDIATE:"I05",INTUITION:"N04",DELIBERATION:"D01",MONITORING:"M05",PERIODIC:"P03",DRIVE:"R02",ENJOY:"E05",SECURE:"S04",OPTIMIZE:"O05"}
} as const;
export const FIXED_SWITCHES = ["SW01","SW02","SW03","SW04","SW05","SW06"] as const;
export const FIXED_BEHAVIORS = ["B01","B02","B03","B04"] as const;
