import type {JobCode,StyleId} from './classifierV1';
import {
  DAILY_SCENE_LIBRARY_SIZE,
  JOB_AXES,
  PUBLIC_TYPE_PATTERN_COUNT,
  PRIMARY_RECOGNITION_HIT_COUNT,
  corePatternForType,
  dailyScenesForType as v6DailyScenesForType,
  type DeepDailyScene,
  type JobAxes,
  type TypeCorePattern,
} from './resultDailySceneNarrativeV6';

export {DAILY_SCENE_LIBRARY_SIZE,JOB_AXES,PUBLIC_TYPE_PATTERN_COUNT,PRIMARY_RECOGNITION_HIT_COUNT,corePatternForType};
export type {DeepDailyScene,JobAxes,TypeCorePattern};

type StyleCode='D'|'E'|'S'|'O';
type TypeKey=`${JobCode}-${StyleCode}`;
type HitScene={label:string;title:string;voice:string;category:string};

const STYLE_CODE:Record<StyleId,StyleCode>={DRIVE:'D',ENJOY:'E',SECURE:'S',OPTIMIZE:'O'};

/**
 * V7 recognition scenes are written as whole moments, not generated by appending
 * a type sentence to a generic template. The scene is hypothetical; it is there
 * to trigger recognition without claiming a specific purchase history.
 */
const HIT_SCENES:Record<TypeKey,[HitScene,HitScene,HitScene]>={
  'FDM-D':[
    {label:'🧑‍💻 仕事道具を買う時',title:'高いかより、「これで仕事が早くなる」が見えた瞬間に決めやすい',voice:'しばらく使えて、毎回の手間が減るなら出していい。',category:'仕事'},
    {label:'📱 スマホを買い替える時',title:'最新だからでは動かない。今より明らかにラクになる機能があると急に前向き',voice:'便利そう、じゃ弱い。毎日ラクになるなら買い替える理由になる。',category:'買い物'},
    {label:'📚 資格・講座に申し込む時',title:'申し込む前はかなり見る。でも「この先使う場面」が浮かぶと決断が早い',voice:'取ることより、取ったあと何に使えるかまで見えたらGO。',category:'自己投資'},
  ],
  'FDM-E':[
    {label:'🏨 旅行のホテルを選ぶ時',title:'予約前に先の予定を一回確認。問題なければ、満足できる方へちゃんと上げる',voice:'あとで困らないなら、せっかくの旅行まで削らなくていい。',category:'旅行'},
    {label:'🎫 ライブ・イベントを取る時',title:'行きたいだけでは押さない。でも先に響かないと分かったら迷いが消える',voice:'予定も支払いも大丈夫。なら行かない理由の方がない。',category:'娯楽'},
    {label:'🍽 少し高い店にする時',title:'安い店も見る。でも先に無理がなければ「今日は満足する方」を選べる',voice:'普段まで削る必要はない。今日はちゃんと楽しみたい。',category:'外食'},
  ],
  'FDM-S':[
    {label:'💳 一括か分割か迷う時',title:'払える金額でも、払った後の余裕が読めないと急に慎重になる',voice:'買える。でも買った後まで平気かが見えないとまだ押せない。',category:'支払い'},
    {label:'🛡 保険を見直す時',title:'安さより「何かあっても困らない線」が見えるまで条件を詰めたくなる',voice:'安くするより、必要なところだけちゃんと残したい。',category:'固定費'},
    {label:'🧊 大きな家電を買う時',title:'必要だから買う。でも買った後の生活費まで頭に入れてから決めたい',voice:'今必要なのは分かる。あとは払った後が普通に回るかだけ。',category:'家電'},
  ],
  'FDM-O':[
    {label:'📱 携帯プランを見直す時',title:'安いプランより「使ってないものに毎月払ってないか」が気になる',voice:'足りないのは困る。でも余ってる分まで払い続ける意味はない。',category:'固定費'},
    {label:'📦 新品か型落ちか迷う時',title:'最新に惹かれても、使わない差しかないと型落ちへ戻れる',voice:'その新機能、しばらく使う？使わないなら差額はいらない。',category:'買い物'},
    {label:'📺 サブスクを整理する時',title:'一度残したサービスでも、役割が薄くなったら普通に切り替えられる',voice:'前は使った。でも今後も払う理由が残ってるかは別。',category:'サブスク'},
  ],

  'FDP-D':[
    {label:'📚 講座に申し込む直前',title:'普段は考えてないのに、申込期限が来ると急に比較表を作りたくなる',voice:'今決めるなら、取ったあと一番使えるものにしたい。',category:'自己投資'},
    {label:'💼 仕事の節目が来た時',title:'転機が来るまで放置。でも動くと決めた日だけ情報収集が一気に進む',voice:'毎日は見ない。今が動く時なら、必要な材料だけ集めて決める。',category:'仕事'},
    {label:'💰 臨時収入が入った時',title:'入った瞬間には使わず、「次に進める使い道」を一回だけ並べたくなる',voice:'せっかく増えたなら、あとで効いてくる使い方に回したい。',category:'収入'},
  ],
  'FDP-E':[
    {label:'🎫 イベントの申込期限前',title:'普段は忘れてるのに締切が近づくと、「行くなら楽しめる方」で急に本気',voice:'今しかないなら、後で思い出して満足する方にしたい。',category:'娯楽'},
    {label:'✈️ 旅行を決める時',title:'予定が固まるまではざっくり。予約日が来ると楽しさと予算をまとめて決める',voice:'毎日考えなくていい。決める日にちゃんと楽しめる形へ整えたい。',category:'旅行'},
    {label:'🎁 ご褒美を決める時',title:'ずっと我慢するより、区切りが来た時に「ここは楽しむ」を作る方が続く',voice:'節目くらいはちゃんと楽しむ。その方が次も頑張れる。',category:'ご褒美'},
  ],
  'FDP-S':[
    {label:'🧾 支払い前に残高を見る時',title:'毎日は見ない。でも大きな支払いの前だけ「この先大丈夫？」をまとめて確認',voice:'今ここで平気って分かれば、またしばらく気にしなくていい。',category:'家計確認'},
    {label:'🆓 無料体験が終わる時',title:'登録中は気にしない。自動更新の前だけ急に「残す理由」を確認する',voice:'今後も使うなら残す。使う場面が浮かばないなら切る。',category:'サブスク'},
    {label:'🔧 壊れた物を直す時',title:'故障した瞬間に、修理代と買い替え後の負担を一気に見て安心ラインを作る',voice:'直すか買うかより、決めた後に困らない形にしたい。',category:'予定外'},
  ],
  'FDP-O':[
    {label:'📺 サブスク更新の時',title:'普段は放置なのに、更新通知が来た日だけ全部の契約を見直したくなる',voice:'今使ってないなら、惰性で次の期間まで残す必要ない。',category:'サブスク'},
    {label:'📈 値上げ通知が来た時',title:'値上げを見た瞬間、「前から払ってたから」は理由にならなくなる',voice:'この新料金でも残す価値ある？なければ今が切り替え時。',category:'固定費'},
    {label:'💳 年会費の請求前',title:'一年ほぼ見てなかったのに、請求前だけ特典を全部使ったか数えたくなる',voice:'持ってる安心感より、実際に使った価値で残すか決めたい。',category:'カード'},
  ],

  'FNM-D':[
    {label:'📱 スマホを買い替える時',title:'スペックはかなり比べる。でも最後は「毎日使う自分」が浮かぶ機種に寄る',voice:'数字は分かった。あとは使ってる自分が前よりラクか。',category:'買い物'},
    {label:'🏠 引っ越し先を決める時',title:'家賃も駅距離も見る。でも内見で違和感が残る部屋は候補から落ちやすい',voice:'条件は通ってる。でも毎日ここに帰る自分がしっくり来るかは別。',category:'住まい'},
    {label:'🧑‍💻 仕事道具を選ぶ時',title:'性能上位より、「これ使ったら仕事のテンポ上がりそう」が最後の決め手になる',voice:'一番高性能じゃなくていい。自分がちゃんと使い切れる方が強い。',category:'仕事'},
  ],
  'FNM-E':[
    {label:'👕 洋服を買う時',title:'値段も用途も見たのに、試着した瞬間「これ着たい」が勝つと決まりやすい',voice:'条件は悪くない。最後は着て出かけたいと思えるか。',category:'ファッション'},
    {label:'🏨 ホテルを選ぶ時',title:'比較サイトでは絞れる。でも最後は写真を見て「ここに帰ってきたい」が残る',voice:'寝られるだけなら他もある。せっかくなら泊まりたいと思える方。',category:'旅行'},
    {label:'💇 美容院・サロンを選ぶ時',title:'料金だけでは決めず、帰る時の仕上がりまで想像できる店を選びやすい',voice:'安いかより、終わったあと自分が満足してるかが大事。',category:'美容'},
  ],
  'FNM-S':[
    {label:'🛏 ベッド・寝具を選ぶ時',title:'価格は許容でも、寝た瞬間の違和感があると「長く使うし」で止まれる',voice:'毎日使うものだから、数字が合っても落ち着かないならやめたい。',category:'住まい'},
    {label:'👟 靴を買う時',title:'見た目が好きでも、歩いた時の小さな不安が残ると決め切れない',voice:'好き。でも長く履いて不安になりそうなら今じゃない。',category:'ファッション'},
    {label:'🛡 保険を選ぶ時',title:'保障内容を読んでOKでも、「これで本当に安心？」が残るともう一回見る',voice:'条件が足りてるだけじゃなく、自分が落ち着ける形まで欲しい。',category:'固定費'},
  ],
  'FNM-O':[
    {label:'👜 バッグ・財布を買う時',title:'機能は十分でも、自分の普段の持ち物が自然に収まる絵が浮かばないと外す',voice:'便利そうより、毎日ちゃんと使ってる自分が見えるか。',category:'ファッション'},
    {label:'📦 新品か型落ちか迷う時',title:'最新の魅力は分かる。でも自分が使わない差なら急にどうでもよくなる',voice:'すごい機能なのは分かる。でも自分の生活には要る？',category:'買い物'},
    {label:'☁️ クラウド容量を増やす時',title:'容量不足は嫌。でも整理せず増やし続ける未来が浮かぶと一回止まる',voice:'増やせば解決。でも今後もずっと増やすだけになるなら違う。',category:'デジタル'},
  ],

  'FNP-D':[
    {label:'✈️ 急に予定が変わった時',title:'最初の計画にこだわらず、「今から一番進む方法」にすぐ組み替えられる',voice:'予定通りじゃなくていい。今の目的に近づくなら変えよう。',category:'予定変更'},
    {label:'🚕 電車かタクシーか迷う時',title:'予定が押した瞬間、移動費より「次に間に合うか」で判断が切り替わる',voice:'今は節約より、遅れず次へ進む方が大事。',category:'移動'},
    {label:'🎟 旅行先で追加体験を入れる時',title:'予定外でも「この体験が旅の目的にハマる」と思うと、その場で組み直せる',voice:'元の予定を守るより、今回の旅が良くなるなら入れたい。',category:'旅行'},
  ],
  'FNP-E':[
    {label:'💬 友達から急に誘われた時',title:'予定は見る。でも無理がなければ「今しかないし」で楽しむ方へ寄せられる',voice:'先に響かないなら、せっかくの誘いまで断らなくていい。',category:'交際'},
    {label:'🎫 当日イベントを見つけた時',title:'計画外でも、その日しかない体験なら予定を動かして入れたくなる',voice:'予定通りより、あとで思い出す方を取りたい。',category:'娯楽'},
    {label:'🍻 飲み会の二軒目',title:'帰る予定でも「今日まだ楽しい」が強いと、明日に無理がない範囲で延長する',voice:'明日が壊れないなら、今日はもう少し楽しんでもいい。',category:'交際'},
  ],
  'FNP-S':[
    {label:'🔧 急な修理が必要な時',title:'予定外の出費でも、今後困らない方法へすぐ組み直せると落ち着く',voice:'想定外だけど、ここで安全な形に戻せるなら大丈夫。',category:'予定外'},
    {label:'🏨 旅行中に予定変更する時',title:'最初の予約に固執せず、疲れや不安が減るなら泊まり方を変えられる',voice:'決めた通りにするより、無理なく続けられる方へ変えたい。',category:'旅行'},
    {label:'💳 支払い方法を変える時',title:'当初の予定より負担が重いと感じたら、後が苦しくない形へ切り替えたくなる',voice:'最初の計画より、その後も普通に回ることの方が大事。',category:'支払い'},
  ],
  'FNP-O':[
    {label:'🛒 ネット通販のカート',title:'一度欲しいと思っても、状況が変わったらカートから普通に外せる',voice:'前は欲しかった。でも今の目的に合わないならもういらない。',category:'買い物'},
    {label:'🆓 無料体験が終わる時',title:'始めた時は必要でも、今の使い方に合わなくなったら更新前に切り替える',voice:'使い続けることより、今の生活に合ってるかを見たい。',category:'サブスク'},
    {label:'📈 値上げ通知が来た時',title:'前の料金で納得していても、条件が変われば判断も変えていいと思える',voice:'前にOKした料金と今の料金は別。今の価値で決め直す。',category:'固定費'},
  ],

  'IDM-D':[
    {label:'🧑‍💻 仕事道具を買う時',title:'困りごとがはっきりした瞬間、比較はするけど決めるまでが急に速い',voice:'今これで詰まってる。解決できるなら先送りする理由がない。',category:'仕事'},
    {label:'💻 PC・タブレットを選ぶ時',title:'全部入りより、「今やりたいことが一番早くなる構成」を選びたくなる',voice:'使わない高性能より、今の作業にちゃんと効く方。',category:'買い物'},
    {label:'🚕 タクシーを使うか迷う時',title:'時間が足りない時は、運賃より「今の予定を守れるか」で決断できる',voice:'今は安さより、遅れず次に動けることの方が価値ある。',category:'移動'},
  ],
  'IDM-E':[
    {label:'🍽 少し高い店にする時',title:'高いからでは止まらない。「今日はその分楽しめる」が通ると出せる',voice:'普段の店でもいい。でも今日は満足する方に払いたい。',category:'外食'},
    {label:'💇 美容院・サロンを選ぶ時',title:'価格は見る。でも満足度が明らかに違うと思うと安い店へは戻りにくい',voice:'安く済ませるより、帰る時にちゃんと満足したい。',category:'美容'},
    {label:'🍱 デリバリーを頼む時',title:'送料で一回「高い」と思う。でも作る気力がない日は、その手間にも払える',voice:'高いのは分かる。でも今日は料理しない時間を買いたい。',category:'食事'},
  ],
  'IDM-S':[
    {label:'📱 スマホを買い替える時',title:'今必要でも、支払った後に余裕がなくなるなら一度止まれる',voice:'必要なのは本当。でも買った後まで普通に過ごせる形にしたい。',category:'買い物'},
    {label:'💳 一括か分割か迷う時',title:'総額だけじゃなく、今の手元を減らしすぎないかまで見て決めたい',voice:'安く終わるかより、払ったあと困らない方が大事。',category:'支払い'},
    {label:'🔧 修理か買い替えか迷う時',title:'目の前の困りごとは早く解決したい。でも次の故障不安まで残る案は選びにくい',voice:'今直るだけじゃなく、その後も安心して使える方にしたい。',category:'予定外'},
  ],
  'IDM-O':[
    {label:'🛒 ネット通販のカート',title:'欲しくて入れたのに、購入直前だけ「今ほんとに使う？」で急に冷静になる',voice:'欲しいのは本当。でも今使う場面が浮かばないなら一旦外す。',category:'買い物'},
    {label:'📱 携帯プランを見直す時',title:'安いプラン探しより、今の使い方に余ってる容量や特典を削りたくなる',voice:'足りればいい。使ってない分まで毎月持つ必要はない。',category:'固定費'},
    {label:'📦 新品か型落ちか迷う時',title:'最新が良く見えても、「今必要な機能」が同じなら型落ちで普通に納得できる',voice:'欲しいのは最新じゃなく、今困ってることを解決できる方。',category:'買い物比較'},
  ],

  'IDP-D':[
    {label:'🚕 電車かタクシーか迷う時',title:'時間がなくなった瞬間だけ比較スイッチが入り、今いちばん効く手段を選ぶ',voice:'普段は気にしない。今困ってるなら早く解決できる方。',category:'移動'},
    {label:'🍱 デリバリーを頼む時',title:'普段は自炊でも、今日は無理だと思った瞬間に「今の手間」をお金で消せる',voice:'今日だけは作らない。今ラクになるならそれでいい。',category:'食事'},
    {label:'🔧 急に物が壊れた時',title:'壊れるまでは放置。でも壊れた瞬間、修理と買い替えを一気に比べて決める',voice:'今使えないのが問題。最短で戻せる現実的な方を選ぶ。',category:'予定外'},
  ],
  'IDP-E':[
    {label:'💬 友達から急に誘われた時',title:'誘われた瞬間はかなり行く気。送信前に明日の予定だけ一回見る',voice:'明日が致命的じゃないなら、今日は行きたい。',category:'交際'},
    {label:'🍻 飲み会の二軒目',title:'帰るつもりでも、その場が楽しいと「もう一軒」が急に現実的になる',voice:'明日の自分には悪いけど、今この流れを切るのも惜しい。',category:'交際'},
    {label:'🎫 ライブ・イベントを見つけた時',title:'予定になかったのに、楽しんでる自分が浮かぶと判断が一気に前へ出る',voice:'金額は見た。行ったら絶対楽しいなら、今決めたい。',category:'娯楽'},
  ],
  'IDP-S':[
    {label:'🔧 急な修理が必要な時',title:'壊れるまでは考えない。でも困った瞬間だけ「無理なく直す方法」に集中できる',voice:'今直したい。でも直した後にお金で困る形は避けたい。',category:'予定外'},
    {label:'🆓 無料体験が終わる時',title:'使ってる間は気にしない。課金直前になって初めて「本当に残す？」を考える',voice:'今困らないなら切ってもいい。必要になったらまた戻せばいい。',category:'サブスク'},
    {label:'🛡 保険の更新時',title:'普段は見ないのに、更新の瞬間だけ「今の安心に本当に必要？」を確認する',voice:'ずっと考えたくない。今ここで大丈夫な線だけ作りたい。',category:'固定費'},
  ],
  'IDP-O':[
    {label:'⭐ 口コミを見続けている時',title:'レビューを延々読むより、今使う条件に関係ない評価は途中から切り捨てる',voice:'みんなの不満より、自分が困る欠点かだけ見ればいい。',category:'買い物比較'},
    {label:'📦 新品か型落ちか迷う時',title:'買う瞬間だけ比較して、今使わない新機能ならその場で候補から外す',voice:'便利そう、では買わない。今使うかどうかだけ。',category:'買い物'},
    {label:'📺 サブスク更新の時',title:'普段は放置でも、更新画面を開いた瞬間だけ不要な契約を一気に切りたくなる',voice:'今使ってないなら、次の更新まで残す理由はない。',category:'サブスク'},
  ],

  'INM-D':[
    {label:'📱 スマホを買い替える時',title:'スペック比較したのに、最後は「これ使ったら毎日ラク」が見えた機種に決まる',voice:'数字は十分見た。あとは今の自分に一番効くか。',category:'買い物'},
    {label:'🧑‍💻 仕事道具を選ぶ時',title:'比較表では僅差でも、触った瞬間「これなら作業が進みそう」で一気に傾く',voice:'理由は後から説明できる。まず使ってる自分が動けそうか。',category:'仕事'},
    {label:'🚕 タクシーを使うか迷う時',title:'金額は気になる。でも今の自分が消耗してると、移動のラクさが急に勝つ',voice:'今これで疲れ切るより、次に動ける状態で着きたい。',category:'移動'},
  ],
  'INM-E':[
    {label:'👕 洋服を買う時',title:'比較はする。でも試着で「今日これ着て帰りたい」が出るとほぼ勝負が決まる',voice:'値段も見た。最後は自分が一番テンション上がるか。',category:'ファッション'},
    {label:'🏨 ホテルを選ぶ時',title:'安い候補も残すのに、写真を見て「ここ泊まりたい」が立つと戻りにくい',voice:'寝るだけなら他もある。でも今回はここで過ごしたい。',category:'旅行'},
    {label:'💄 コスメ・美容を選ぶ時',title:'口コミを見ても、最後は使った時の気分まで想像できるものが残る',voice:'評判がいいだけじゃなく、自分が使って気分いい方が欲しい。',category:'美容'},
  ],
  'INM-S':[
    {label:'👟 靴を買う時',title:'条件は悪くないのに、履いた瞬間の小さな違和感があると急に買えなくなる',voice:'見た目は好き。でもこの違和感を毎回気にする未来は嫌。',category:'ファッション'},
    {label:'🛏 寝具を選ぶ時',title:'価格も機能も納得していても、「なんか落ち着かない」が残ると保留できる',voice:'数字ではOK。でも毎日使って不安が残るならまだ違う。',category:'住まい'},
    {label:'🔧 修理か買い替えか迷う時',title:'安い修理案があっても、「またすぐ壊れそう」が頭に残ると新品へ寄る',voice:'安く直るより、決めた後に安心して忘れられる方がいい。',category:'予定外'},
  ],
  'INM-O':[
    {label:'🛒 ネット通販のカート',title:'カートまでは勢い。購入ボタンの前だけ「これ本当に使う？」が急に入る',voice:'欲しい。でも届いたあと使ってる自分が浮かばないならやめる。',category:'買い物'},
    {label:'⭐ 口コミを見続けている時',title:'高評価を読んでも決め切れず、「自分が困る欠点だけ」を探し始める',voice:'人気かより、自分の使い方でストレスないかが知りたい。',category:'買い物比較'},
    {label:'📱 携帯プランを見直す時',title:'細かい料金表より、今の生活で使ってないものがあると急に削りたくなる',voice:'安さより、今の自分に余計なものが乗ってないか。',category:'固定費'},
  ],

  'INP-D':[
    {label:'🚕 電車かタクシーか迷う時',title:'予定が詰まった瞬間、普段なら使わない選択肢でも「今ラクなら」で決められる',voice:'今止まってるのが一番もったいない。動ける方へ行く。',category:'移動'},
    {label:'📱 急に必要な物を買う時',title:'必要になるまでは見ない。でも必要になった瞬間、比較は短く決断は速い',voice:'今使う。条件も足りてる。ならもう決めていい。',category:'買い物'},
    {label:'📲 アプリを有料版にする時',title:'何度も同じ制限に引っかかった瞬間、「もう払って消そう」で課金できる',voice:'今この手間が邪魔。毎回止まるくらいなら払って進みたい。',category:'デジタル'},
  ],
  'INP-E':[
    {label:'💬 友達から急に誘われた時',title:'誘いの通知を見た瞬間、予定より先に「行きたい」が立ち上がる',voice:'明日さえ何とかなるなら、今日は行きたい。',category:'交際'},
    {label:'🍻 飲み会の二軒目',title:'帰る理由は分かってる。でも今が楽しいと「もう少し」が普通に勝つ',voice:'明日のことは分かる。でも今ここで帰るのも違う。',category:'交際'},
    {label:'🎫 当日イベントを見つけた時',title:'計画になかったのに、楽しんでる自分が浮かぶと一気に行く気になる',voice:'今しかないなら、考え続けるより行って楽しみたい。',category:'娯楽'},
  ],
  'INP-S':[
    {label:'🔧 急に物が壊れた時',title:'壊れるまでは気にしない。でも壊れた瞬間は「今安心できる解決」をすぐ探す',voice:'普段は考えたくない。今ここで困らない状態に戻したい。',category:'予定外'},
    {label:'🆓 無料体験が終わる時',title:'使ってる間は気にしないのに、課金直前だけ急に「残すと安心？」を考える',voice:'なくして困るなら残す。困らないなら今切っていい。',category:'サブスク'},
    {label:'✈️ 急な旅行に誘われた時',title:'行きたい気持ちは早い。でも予約ボタン前だけ「帰ってから困らない？」が入る',voice:'行きたい。でも帰ってから不安になる形だけは避けたい。',category:'旅行'},
  ],
  'INP-O':[
    {label:'🛒 ネット通販のカート',title:'欲しい時は早い。でも購入直前に「今使う？」がNOだとその場で外せる',voice:'欲しい気持ちはある。でも今使わないなら今日は買わない。',category:'買い物'},
    {label:'📈 値上げ通知が来た時',title:'普段は放置。でも値上げ通知を見た瞬間だけ「まだ要る？」が急に発動する',voice:'前は残した。でも今この値段で使う理由ある？',category:'固定費'},
    {label:'📺 サブスク更新の時',title:'細かく管理しない代わりに、更新画面を開いた時だけ不要なものを一気に切る',voice:'今使ってるかだけ見たい。使ってないなら残さない。',category:'サブスク'},
  ],
};

function key(job:JobCode,style:StyleId):TypeKey{return `${job}-${STYLE_CODE[style]}` as TypeKey}

function asScene(hit:HitScene):DeepDailyScene{
  return {
    label:hit.label,
    title:hit.title,
    voice:`「${hit.voice}」`,
    category:hit.category,
    body:'日常の具体的な判断場面を通して、そのTYPEの意思決定のクセが出やすい瞬間を描いた認知用シーンです。実際にこの買い物や行動をしたと断定するものではありません。',
    insight:'このシーンは、診断で測定した時間視野・判断根拠・把握リズムとPrimary STYLEの組み合わせから表現しています。特定の商品を買う頻度、所得、浪費傾向など未測定の事実は推定していません。',
  };
}

function pickExtras(jobCode:JobCode,style:StyleId,used:DeepDailyScene[],needed:number){
  if(needed<=0)return [] as DeepDailyScene[];
  const pool=v6DailyScenesForType(jobCode,style,12);
  const labels=new Set(used.map(x=>x.label.replace(/^\S+\s+/,'')));
  const categories=new Set(used.map(x=>x.category));
  const picked:DeepDailyScene[]=[];
  for(const scene of pool){
    const plain=scene.label.replace(/^\S+\s+/,'');
    if(labels.has(plain)||categories.has(scene.category))continue;
    picked.push(scene);labels.add(plain);categories.add(scene.category);
    if(picked.length>=needed)return picked;
  }
  for(const scene of pool){
    const plain=scene.label.replace(/^\S+\s+/,'');
    if(labels.has(plain)||picked.includes(scene))continue;
    picked.push(scene);labels.add(plain);
    if(picked.length>=needed)return picked;
  }
  return picked;
}

export function dailyScenesForType(jobCode:JobCode,style:StyleId,count=6):DeepDailyScene[]{
  const hits=HIT_SCENES[key(jobCode,style)].map(asScene);
  if(count<=3)return hits.slice(0,count);
  return [...hits,...pickExtras(jobCode,style,hits,count-3)].slice(0,count);
}

export function humanRecognitionScenesForType(jobCode:JobCode,style:StyleId){
  return HIT_SCENES[key(jobCode,style)];
}

export const HUMAN_RECOGNITION_SCENE_COUNT=Object.values(HIT_SCENES).reduce((n,x)=>n+x.length,0);
